security:
    role_hierarchy:
        ROLE_ADMIN: [ 'ROLE_ALLOWED_TO_SWITCH','ROLE_USER' ]
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        hwi:
            id: spl.user_provider

    firewalls:
        secured_area:
            switch_user: ~
            oauth:
                resource_owners:
                    aai_eosc: "/oauth/callback"
                login_path:        /connect/aai_eosc
                use_forward:       true
                failure_path:      /connect/aai_eosc
                oauth_user_provider:
                    service: spl.user_provider
            logout:
                path:   /oauth/logout
                target: /
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/connect/aai_eosc, roles: PUBLIC_ACCESS }
        - { path: ^/(.+), roles: ROLE_USER }
